### ISSUE TITLE
Classes and IDs

### ISSUE THREAD

**Issue by ghost** [santiagobs/teacozy#5]
https://github.com/santiagobs/teacozy/blob/master/index.html#L38-L85

Try to be consistent with your naming conventions, like when choosing to name one flex-container `flextea` and another `locationsflex`. Small details like these could potentially distract or confuse another programmer using your code and potentially cause bugs, but at the very least most company style guides will just expect you to be consistent out of preference.

Try to use simple classes and IDs. You generally don't need to use the word `box` in all your classes and IDs... since all HTML elements are basically boxes. It's a bit redundant and it doesn't really say anything about your content. Same for using `flex` for every flex-item. Just indicate the flex-container and it's implied that its children are flex-items.

**Comment by santiagobs** [comment]
I will take it into account, thank you.
